# Generated by Django 5.0 on 2023-12-07 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiverProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functional_sac_rate', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('deco_sac_rate', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('min_gas_sac', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
